---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# publicationsscraper

<!-- badges: start -->
<!-- badges: end -->

# Research and CRAN Publications Retrieval Package

## Overview

The publicationsscraper R package offers tools to retrieve research publications from Google Scholar and ORCID, along with CRAN package download statistics. It is tailored for academic researchers in the EBS department who wish to consolidate and analyze their research outputs, while also monitoring their contributions to CRAN, including publication updates and downloads.

The main functions included are:
- `find_cran_packages`: Searches for CRAN packages by an author's first and last name and returns relevant package information such as the number of downloads and last update date.
- `get_publications`: Retrieves publications from both Google Scholar and ORCID based on provided IDs.
- `get_all_publications`: Retrieves publications from multiple authors.
- `cran_all_pubs`: Combines CRAN package data for multiple authors.

## Installation

To install this package, you can clone the repository and load the package using:

```r
# Clone the repository
git clone <https://github.com/numbats/achievement-scraper.git>

# Install required packages
install.packages(c("pkgsearch", "tibble", "dplyr", "stringr", "scholar", "rorcid"))

# Load the package
devtools::load_all()

```

## Functions



