---
title: "Visualisations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{visualisations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r loading libraries}
library(publicationsscraper)
library(ggplot2)
```


```{r}
# Publications of each author by year
get_publications("0000-0002-2140-5352", "vamErfkAAAAJ") |>
  dplyr::filter(!is.na(publication_year)) |>
  dplyr::count(publication_year) |>
  ggplot(aes(x = as.numeric(publication_year), y = n)) +  
  geom_line(color= "red") +
  theme_minimal() +
  labs(title = "Publications Over Time", x = "Year", y = "Number of Publications")
```

```{r}
# Define cran_authors
cran_authors <- tibble::tibble(
  first_name = c("Michael", "Rob"),
  last_name = c("Lydeamore", "Hyndman")
)
# Top Packages by Number of Downloads
cran_all_pubs(cran_authors) |>
  dplyr::arrange(desc(downloads)) |>
  dplyr::top_n(10, downloads) |>
  ggplot(aes(x = reorder(name, downloads), y = downloads)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Top 10 Packages by Downloads", x = "Package Name", y = "Downloads")
```
```{r}
# Top 5 CRAN Packages by Downloads (Monash EBS Staff)

ebs_authors <- tibble::tibble(
  first_name = c("Akanksha", "Alan", "Andrew", "Ann", "Athanasios", 
                 "Benjamin", "Bin", "Brett", "Catherine", "Charanjit", 
                 "Damjan", "Dan", "Daniel", "David", "Didier", 
                 "Donald", "Duangkamon", "Farshid", "Gael", "George", 
                 "Geraldine", "Hamza", "Heather", "Hsein", "Jack", 
                 "Jackie", "Janjala", "Jessica", "Jiti", "Joan", "John", 
                 "Julie", "Kate", "Keith", "Klaus", "Maxwell", "Maziar", 
                 "Mervyn", "Natalia", "Ole", "Otavio", "Param", 
                 "Ralph", "Rami", "Robert", "Ruben", "Shanika", 
                 "Tissa", "Wei", "Xibin", "Xueyan", "Yu"),
  last_name = c("Negi", "Powell", "Matthews", "Maharaj", "Pantelous", 
                "Wong", "Peng", "Inder", "Forbes", "Kaur", 
                "Vukcevic", "Zhu", "Melser", "Frazier", "Nibbering", 
                "Poskitt", "Chotikapanich", "Vahid-Araghi", "Martin", "Athanasopoulos", 
                "Roberts", "Hanbali", "Anderson", "Kew", "Jewson", 
                "Li", "Chirakijja", "Leung", "Gao", "Tan", "Stapleton", 
                "Cook", "Saunders", "McLaren", "Ackermann", "King", "Nikpour", 
                "Silvapulle", "Bailey", "Maneesoonthorn", "Bartalotti", "Silvapulle", 
                "Snyder", "Tabri", "Brooks", "Loaiza Maya", "Wickramasuriya", 
                "Galagedera", "Wei", "Zhang", "Zhao", "Bai")
)

# Retrieve Monash EBS authors
cran_data <- cran_all_pubs(ebs_authors)

top_packages <- cran_data |>
  dplyr::group_by(name) |>
  dplyr::summarise(total_downloads = sum(downloads, na.rm = TRUE)) |>
  dplyr::arrange(desc(total_downloads)) |>
  dplyr::top_n(5, total_downloads)

ggplot(top_packages, aes(x = reorder(name, total_downloads), y = total_downloads)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  labs(title = "Top 5 CRAN Packages by Monash EBS Staff", 
       x = "Package Name", 
       y = "Downloads") +
  theme_minimal()

```

```{r}
# Total Downloads by Author
cran_all_pubs(cran_authors) |>
  dplyr::mutate(authors = stringr::str_extract(authors, "[^\\[]+")) |>
  dplyr::group_by(authors) |>
  dplyr::summarise(total_downloads = sum(downloads, na.rm = TRUE)) |>
  dplyr::arrange(desc(total_downloads)) |>
  ggplot(aes(x = reorder(authors, total_downloads), y = total_downloads)) +
  geom_bar(stat = "identity", fill = "hotpink") +
  coord_flip() +
  theme_minimal() +
  labs(title = "Total Downloads by Author", x = "Author", y = "Total Downloads")

```


```{r}
# Top 10 Authors by Number of Publications
get_all_publications(orcid_ids, scholar_ids) |>
  tidyr::separate_rows(authors, sep = ", ") |>
  dplyr::count(authors, sort = TRUE) |>
  dplyr::top_n(10, n) |>
  ggplot(aes(x = reorder(authors, n), y = n)) +
  geom_bar(stat = "identity", fill = "purple") +
  coord_flip() +
  theme_minimal() +
  labs(title = "Top 10 Authors by Number of Publications", x = "Author", y = "Number of Publications")
```


```{r}
library(ggplot2)
library(lubridate)
cran_all_pubs(cran_authors) |>
  dplyr::mutate(last_update_date = lubridate::ymd_hms(last_update_date)) |>
  dplyr::arrange(last_update_date) |>
  ggplot(aes(x = last_update_date, y = downloads, group = 1)) + 
  geom_line(color = "blue", size = 1) +
  theme_minimal() +
  labs(title = "Downloads Over Time", x = "Last Update Date", y = "Downloads")

```





